Feat/klivvr picks
Klivvr-OS/klivvr-community-be pull request #19
Opened 2023-08-10 13:44 UTC by johnnabil

## ℹ️ PR Info
### 📄 Description 

  ##### Why do we need this change?
This PR is for adding the Klivvr Pick feature in the app by:
- Introduced a nominated attribute for users and a dedicated table for Klivvr Picks.
- Introduced a nominated attribute for users and a dedicated table for Klivvr Picks, enhancing data structure.
- Added jwt-auth.ts, centralizing token-related functions.
- Established KlivvrPickRepo and KlivvrPickService for streamlined CRUD operations related to Klivvr Picks. 
- Nominated user privileges for CRUD operations and added exclusive moderator-controlled nomination functions.
- Developed a weekly Klivvr Picks retrieval function, aligned with a Thursday-to-Wednesday cycle

2023-08-10 18:40 UTC, kerolloz commented on src/database/prisma/schema.prisma
> +  nominated         Boolean            @default(false)
Not the best way to do it. Let's go with a separate table klivvr picks nominations, it could have the following attributes: startDate, endDate, nominee, nominator

and link the nomination to the picks. A boolean in the Users table doesn't make sense.

2023-08-10 18:42 UTC, kerolloz commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
Hmmm, but the PICKS_MODERATOR is just a normal user, no?

2023-08-10 18:43 UTC, kerolloz commented on src/middlewares/jwt-auth.ts
> +};
do we use this?

2023-08-10 18:47 UTC, kerolloz commented on src/routes/klivvrPickRouter.ts
> +    }
create a findOneWithError method and throw the error inside the method and query should be both the pickId and the userId

2023-08-10 18:47 UTC, kerolloz commented on src/routes/userRouter.ts
> +          KlivvrPicks: true,
why?

2023-08-13 08:54 UTC, johnnabil commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
Yes, but he is the only one that has the privilege of nominating the users, isn't this like ramzy's role? that is what I understood when i talked with him

2023-08-13 09:08 UTC, kerolloz commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
cool, but you will also need to allow him to do everything that a normal user can do, so think about it again.

2023-08-13 09:10 UTC, johnnabil commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
he can do what any other user can do, he can be nominated, he can add his own klivvr picks, he can do anything, the only difference is that only he can nominate others

2023-08-13 09:38 UTC, johnnabil commented on src/routes/userRouter.ts
> +          KlivvrPicks: true,
why not, if I want to discover another user's profile, it could be fun to know what this user recommended in his previous klivvr picks

2023-08-13 13:29 UTC, kerolloz commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
Well, that means you'll need to check for every normal endpoint that the user role is any of (moderator, or user) and only for the `nominate` endpoint the role is (moderator). Which doesn't look like an optimal solution.

2023-08-13 13:30 UTC, kerolloz commented on src/routes/userRouter.ts
> +          KlivvrPicks: true,
okay cool, name it `klivvrPicks`

2023-08-13 13:48 UTC, johnnabil commented on src/database/prisma/schema.prisma
> +  PICK_MODERATOR
As I understand, I don't need to check the user role in any endpoint, except the ones that I want to check like this one.
As an example like `isAuth`, I don't add them to the endpoint register or login as I don't need to check if the user is authenticated, the same idea here, I don't need to check if the user is a Pick moderator except the function where the Moderator can call this function

2023-08-15 14:28 UTC, msherifs requested changes

2023-08-15 14:28 UTC, msherifs commented on src/middlewares/jwt-auth.ts
> +};
1. Why writing two functions for each middleware ? (`isAuth`, and `isAuthenticated` for an example) 
2. I've noticed you are checking for isAuthenticated for each middleware, in express you could chain as many middleware as you want, in the route declaration

2023-08-15 14:28 UTC, msherifs commented on src/routes/klivvrPickRouter.ts
> +  isAuth,
you could assign a middleware for all the routes, i think this will be better for the auth middleware 
in the root router you could register the non authenticated routes first, then use the middleware, then register the protected routes
as an example:
```
router.use('/auth', authRouter);
router.use(isAuth);
router.use('/users', userRouter);
```

2023-08-15 14:45 UTC, johnnabil commented on src/middlewares/jwt-auth.ts
> +};
my point of view was that authenticateUser returns the user and isAuth is like the other middlewares (isNominated and verifyModerator) is used to call the authenticate user function

2023-08-15 16:32 UTC, msherifs commented on src/middlewares/jwt-auth.ts
> +};
by that, the functionality of `authenticateUser` is not a middleware and should belong to the service.
also no need to call `authenticate`, as the authentication middleware will be called automatically in the beginning of the request pipeline

2023-08-17 09:55 UTC, msherifs approved these changes

2023-08-17 10:09 UTC, mohamadelhinamy approved these changes

2023-08-17 10:09 UTC, merged